/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Experiment: typeof import('./src/components/Experiment.vue')['default']
    ExperimentEnd: typeof import('./src/components/ExperimentEnd.vue')['default']
    ExpInstruct: typeof import('./src/components/ExpInstruct.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
